### ISSUE TITLE
Add a higher level fuzzy deduplication module

### ISSUE THREAD

**Issue by ayushdg** [NVIDIA/NeMo-Curator#11]
Currently fuzzy deduplication is a combination of multiple steps (minhashes, LSH) etc. that are applied independently.

There should be a higher level fuzzy deduplication module that calls these individual steps based on provided parameters.

**Comment by elliottnv** [comment]
Not sure if it can be merged tomorrow. Its targeting the 05/03 code freeze on NMFW 24.05.

**Comment by ayushdg** [comment]
Completed via #46
