### ISSUE TITLE
Error starting dask cuda worker with nemo framework container

### ISSUE THREAD

**Issue by yyu22** [NVIDIA/NeMo-Curator#143]
**Describe the bug**
using the slurm script for starting dedup jobs run into errors starting dask cuda workers.
```
Traceback (most recent call last):
  File "/usr/local/bin/dask-cuda-worker", line 5, in <module>
	from dask_cuda.cli import worker
  File "/usr/local/lib/python3.10/dist-packages/dask_cuda/cli.py", line 61, in <module>
	@cuda.command(name="worker", context_settings=dict(ignore_unknown_options=True))
AttributeError: 'function' object has no attribute 'command'
```

**Steps/Code to reproduce bug**

```
if [[ $DEVICE == 'gpu' ]]; then
	dask-cuda-worker \
	--scheduler-file $SCHEDULER_FILE \
	--rmm-pool-size $RMM_WORKER_POOL_SIZE \
	--interface $INTERFACE \
	--rmm-async >> $WORKER_LOG 2>&1 &
fi
```
This happened with nemo framework container (either dev or 24.05 version). The issue can be resolved by upgrading dask and dask-cuda before starting the workers:
`bash -c "pip install --upgrade dask dask-cuda"`

**Comment by glam621** [comment]
Assigning to @VibhuJawa

**Comment by VibhuJawa** [comment]
Should probably have been closed by: https://github.com/NVIDIA/NeMo/pull/9580

@yyu22 , Can we confirm this ?

**Comment by ryantwolf** [comment]
Closing as resolved.
