### ISSUE TITLE
Reading compressed json files

### ISSUE THREAD

**Issue by yyu22** [NVIDIA/NeMo-Curator#145]
**Is your feature request related to a problem? Please describe.**
raw downloaded Red Pajama V2 data is stored in json.gz. Curator does not support reading from compressed json.

**Describe the solution you'd like**
support for reading compressed json files

**Describe alternatives you've considered**
first decompress using bash commands and then read the decompressed data.

**Comment by glam621** [comment]
Check in with @yyu22 to close this.

**Comment by yyu22** [comment]
yes this can be close as dask can read compressed json
