### ISSUE TITLE
KeyError in Map Buckets

### ISSUE THREAD

**Issue by yyu22** [NVIDIA/NeMo-Curator#149]
**Describe the bug**

In [map_buckets.py](https://github.com/NVIDIA/NeMo-Curator/blob/main/nemo_curator/scripts/fuzzy_deduplication/map_buckets.py#L62), `text_field` arg is not specified and the class _MapBuckets has [`text_field`](https://github.com/NVIDIA/NeMo-Curator/blob/main/nemo_curator/modules/fuzzy_dedup.py#L547) defaults to “text”. This will cause a KeyError if `text_field` is not "text"

**Steps/Code to reproduce bug**

```
    map_buckets = _MapBuckets(
        id_fields=["dataset_id", "doc_id"],
        bucket_field=input_bucket_field,
    )
```

**Expected behavior**
set the `text_field` to the `input_text_field`
```
    map_buckets = _MapBuckets(
        id_fields=["dataset_id", "doc_id"],
        bucket_field=input_bucket_field,
        text_field=input_text_field,
    )
```

**Comment by glam621** [comment]
Follow up with @yyu22 and @ryantwolf

**Comment by yyu22** [comment]
fixed in PR https://github.com/NVIDIA/NeMo-Curator/pull/196
