### ISSUE TITLE
Default int_to_str_id error in jaccard shuffle

### ISSUE THREAD

**Issue by yyu22** [NVIDIA/NeMo-Curator#150]
**Describe the bug**

In [jaccard_shuffle.py](https://github.com/NVIDIA/NeMo-Curator/blob/main/nemo_curator/scripts/fuzzy_deduplication/jaccard_shuffle.py#L62), the `int_to_str_id` pass to `_Shuffle()` default to "adlr_id". This will cause the `anchor_id_fields` to be wrong in [jaccard_compute.py](https://github.com/NVIDIA/NeMo-Curator/blob/main/nemo_curator/scripts/fuzzy_deduplication/jaccard_compute.py#L43) if the `input_json_id_field` is not set to "adlr_id".

For example, if the true `input_json_id_field` is "id" and `int_to_str_id` is "adlr_id", running jaccard_compute will get an error:
```
KeyError: "columns {'anchor_0_id', 'anchor_1_id', 'id'} do not exist"
```

**Steps/Code to reproduce bug**

```
    shuffle = _Shuffle(
        id_fields=["dataset_id", "doc_id"],
        text_field=args.input_json_text_field,
        profile_dir=args.profile_path,
        int_to_str_id="adlr_id",
    )
```

```
    jaccard = JaccardSimilarity(
        id_field=args.input_json_id_field,
        text_field=args.input_json_text_field,
        anchor_id_fields=[f"anchor_{i}_{args.input_json_id_field}" for i in range(2)],
        ngram_width=args.ngram_size,
    )
```

**Expected behavior**

`int_to_str_id` should be consistent with `args.input_json_id_field`

**Comment by sarahyurick** [comment]
Working on this, should open a PR in the next day or so.
