### ISSUE TITLE
Semantic Deduplication Docs not in Index

### ISSUE THREAD

**Issue by ryantwolf** [NVIDIA/NeMo-Curator#197]
**Describe the bug**

The semantic deduplication documentation does not appear in the https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/index.html or on the sidebar on the page.

**Steps/Code to reproduce bug**

Go to https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/index.html.

**Expected behavior**

Going to https://docs.nvidia.com/nemo-framework/user-guide/latest/datacuration/index.html should have the semantic deduplication documentation accessible on the sidebar

**Environment overview (please complete the following information)**
N/A

**Environment details**
N/A

**Comment by VibhuJawa** [comment]
PR: https://github.com/NVIDIA/NeMo-Curator/pull/225
