### ISSUE TITLE
Make `max_text_bytes_per_part` configurable

### ISSUE THREAD

**Issue by ayushdg** [NVIDIA/NeMo-Curator#233]
**Is your feature request related to a problem? Please describe.**
#77 adds support for longer strings and as a part of those discussions it makes sense to expose some advanced config options to users as well: https://github.com/NVIDIA/NeMo-Curator/pull/77#discussion_r1747727708.

**Describe the solution you'd like**
Expose these hardcoded values as config options that can be tweaked if needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by sarahyurick** [comment]
Closing in favor of https://github.com/NVIDIA/NeMo-Curator/issues/331.
