### ISSUE TITLE
[FEA] Adding Dockerfile to build a nemo-curator container

### ISSUE THREAD

**Issue by miguelusque** [NVIDIA/NeMo-Curator#25]
**Is your feature request related to a problem? Please describe.**
Hi!

I think that it might be useful to have a Dockerfile that allows to build a docker image containing only NeMo-Curator and its dependencies.

The rationale behind this request is to have a slim version of NeMo-Curator container.

I also think that it might be awesome if a NeMo-Curator-only container might also be hosted at NGC.

**Describe alternatives you've considered**
I have created the following Dockerfile, and I am now testing it:

```
# Use nvcr.io/nvidia/pytorch:24.03-py3 as the base docker image
FROM nvcr.io/nvidia/pytorch:24.03-py3

# Set the working directory to /opt
WORKDIR /opt

# Clone the specified git repository into the /opt folder
RUN git clone https://github.com/NVIDIA/NeMo-Curator.git

# Set the working directory to the cloned repository
WORKDIR /opt/NeMo-Curator

# Install the Python package in editable mode with the specified extra index URL
RUN pip install --extra-index-url https://pypi.nvidia.com --editable .
```

**Additional context**
Great job! Thank you!

**Comment by ryantwolf** [comment]
I think we're going to omit a Dockerfile for the time being in favor of the pip installation path we already have along with the NeMo dev container.
