### ISSUE TITLE
Japanese support for get_word_splitter

### ISSUE THREAD

**Issue by oumugai** [NVIDIA/NeMo-Curator#257]
Is your feature request related to a problem?
I am frustrated that the get_word_splitter function does not handle Japanese text correctly. For example, Japanese does not have spaces between words, so the current logic does not accurately determine word separations. This can result in inaccurate results being returned for certain natural language processing tasks.

Describe the solution you'd like
We would like to implement get_word_splitter specifically for Japanese. Japanese word splitting requires morphological analysis, so libraries such as Kuromoji.js and MeCab should be used to properly split Japanese text.

**Comment by sarahyurick** [comment]
Thanks for raising this issue! Currently working on a solution that uses [MeCab](https://pypi.org/project/mecab-python3/) like you suggested.

**Comment by sarahyurick** [comment]
Hi @oumugai we have tested and merged https://github.com/NVIDIA/NeMo-Curator/pull/320 for splitting Japanese text. Please let me know if you have any other issues.
