### ISSUE TITLE
Improve NeMo Curator Experience for Pytorch Models (with crossfit)

### ISSUE THREAD

**Issue by VibhuJawa** [NVIDIA/NeMo-Curator#288]
**Is your feature request related to a problem? Please describe.**

Based on user feedback we need to fix the following to make user experience better: 

- [x] [Enable PyTorch to share same memory pool as RMM via cli #1392](https://github.com/rapidsai/dask-cuda/pull/1392)
PR in `dask-cuda` merged, will follow up for curator in next release
- [x] [Fix GPU-id logging of crossfit](https://github.com/rapidsai/crossfit/pull/95)
- [x] [Enable  memory estimation of crossfit+PyTorch when RMM backend is used](https://github.com/rapidsai/crossfit/pull/94)

**Comment by Christina-Young-NVIDIA** [comment]
At risk because not all items above will complete in this sprint.  Vibhu to break into two issues.

**Comment by sarahyurick** [comment]
All subtasks are completed.
