### ISSUE TITLE
Cannot run `gpu_exact_dups` due to deprecated flag

### ISSUE THREAD

**Issue by davzoku** [NVIDIA/NeMo-Curator#350]
**Describe the bug**

Hi, I was running exact dedup using Nemo Curator and I notice that `gpu_exact_dups` cannot be executed as expected.

**Steps/Code to reproduce bug**

Prereqs:
- `add_id` is executed on the jsonl to add id for dedup
- existing `.jsonl` files in file directory eg.`books_dedup/`

1. Run

```
gpu_exact_dups \
 --input-json-id-field="nemo_id" \
 --input-data-dir=books_dedup/ \
 --output-dir=exact_dedup \
 --device=gpu \
> logs/exact_dedup.log 2>&1
```

2. Check Logs for Error

```
Traceback (most recent call last):
  File "/home/ubuntu/efs/envs/nemo_curator_org2/bin/gpu_exact_dups", line 8, in <module>
    sys.exit(console_script())
  File "/home/ubuntu/efs/envs/nemo_curator_org2/lib/python3.10/site-packages/nemo_curator/scripts/find_exact_duplicates.py", line 110, in console_script
    main(attach_args().parse_args())
  File "/home/ubuntu/efs/envs/nemo_curator_org2/lib/python3.10/site-packages/nemo_curator/scripts/find_exact_duplicates.py", line 62, in main
    backend="pandas" if args.no_gpu else "cudf",
AttributeError: 'Namespace' object has no attribute 'no_gpu'
```

Notice that there is an error due to `no_gpu` attribute.

**Expected behavior**

`gpu_exact_dups` should be completed without errors.

**Environment overview (please complete the following information)**

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider - AWS, Azure, GCP, Collab)]
 - Method of NeMo-Curator install: [pip install or from source]. Please specify exact commands you used to install.
 - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version Ubuntu 22.04
- Dask version: 2024.7.1
- Python version: 3.10

**Additional context**

NA

**Comment by VibhuJawa** [comment]
Close by [Fix gpu_exact_dups due to deprecated flag #351](https://github.com/NVIDIA/NeMo-Curator/pull/351)
