### ISSUE TITLE
[BUG] Jaccard Shuffle error if merge result is empty

### ISSUE THREAD

**Issue by ayushdg** [NVIDIA/NeMo-Curator#49]
**Describe the bug**

If the merge result b/w text and bucket mapping df is empty for any iteration the logic fails.

Failure is observed here but originates from https://github.com/NVIDIA/NeMo-Curator/blob/fe9fd6f46a932689ba036c623b2737298478c8ea/nemo_curator/utils/fuzzy_dedup_utils/shuffle_utils.py#L144 being empty.
Still working on a minimal repro.

**Additional context**

The fix should be to continue on with the loop if this is a 0 len df.

Error here looks like `ValueError: zero-size array to reduction operation maximum which has no identity`

## Update 10/28
1. #316 fixes it, and I'm trying another method. However in case the another method doesn't work our we'll go ahead with fixing this.

**Comment by glam621** [comment]
Will be assigning to Vibhu to investigate.

**Comment by ryantwolf** [comment]
@VibhuJawa has a fix that needs testing.

**Comment by VibhuJawa** [comment]
Will be probably covered by: https://github.com/NVIDIA/NeMo-Curator/issues/240
