### ISSUE TITLE
[FEA] Make classifiers work with HuggingFace directly

### ISSUE THREAD

**Issue by VibhuJawa** [NVIDIA/NeMo-Curator#72]
With PR https://github.com/NVIDIA/NeMo-Curator/pull/58, we have cleaned up the model initialization quite a bit.  We still need to make the classifiers work directly with HuggingFace without downloading weights. 

We should do that once we upload the models to HF. 

See comment here: 
https://github.com/NVIDIA/NeMo-Curator/pull/58#discussion_r1605342515

**Comment by sarahyurick** [comment]
Once this is done, we can also update https://github.com/NVIDIA/NeMo-Curator/blob/main/tutorials/distributed_data_classification/distributed_data_classification.ipynb and https://github.com/NVIDIA/NeMo-Curator/blob/main/docs/user-guide/DistributedDataClassification.rst accordingly.

**Comment by sarahyurick** [comment]
Can start working on this now that we have https://huggingface.co/nvidia/domain-classifier

**Comment by VibhuJawa** [comment]
Yes please, @sarahyurick , Do you have band-width to start on this, happy to jump on it if not.

**Comment by sarahyurick** [comment]
> Yes please, @sarahyurick , Do you have band-width to start on this, happy to jump on it if not.

Yes, happy to work on this.

**Comment by sarahyurick** [comment]
Linking to https://github.com/NVIDIA/NeMo-Curator/issues/71.

We should be able to get labels from HF directly (https://huggingface.co/nvidia/domain-classifier) as they are present in `config.id2label`.
