### ISSUE TITLE
Where to obtain domain and quality model files?

### ISSUE THREAD

**Issue by randerzander** [NVIDIA/NeMo-Curator#86]
I'm trying to follow the [data classification tutorial](https://github.com/NVIDIA/NeMo-Curator/blob/main/tutorials/distributed_data_classification/distributed_data_classification.ipynb),  which refers to some .pth model files.

Where can I obtain these from? I'd have expected the library to automatically pull them from Hugging Face?

**Comment by ayushdg** [comment]
Possibly a duplicate of #72

**Comment by ryantwolf** [comment]
Domain classifier available [here](https://huggingface.co/nvidia/domain-classifier/blob/main/model.pth). I will close the issue when we release the quality classifier as well.

**Comment by ryantwolf** [comment]
Quality classifier available [here](https://huggingface.co/nvidia/quality-classifier-deberta). Both domain and quality now automatically download from Hugging Face too with #190.
